<?php

/** ******************************************************************************* *
  *                    !ATENCION!                                                   *
  *                                                                                 *
  * Este codigo es generado automaticamente. Si lo modificas tus cambios seran      *
  * reemplazados la proxima vez que se autogenere el codigo.                        *
  *                                                                                 *
  * ******************************************************************************* */

/** ProblemsTags Data Access Object (DAO) Base.
 *
 * Esta clase contiene toda la manipulacion de bases de datos que se necesita
 * para almacenar de forma permanente y recuperar instancias de objetos
 * {@link ProblemsTags}.
 * @access public
 * @abstract
 *
 */
abstract class ProblemsTagsDAOBase {
    /**
     * Guardar registros.
     *
     * Este metodo guarda el estado actual del objeto {@link ProblemsTags}
     * pasado en la base de datos. La llave primaria indicará qué instancia va
     * a ser actualizada en base de datos. Si la llave primara o combinación de
     * llaves primarias que describen una fila que no se encuentra en la base de
     * datos, entonces save() creará una nueva fila, insertando en ese objeto
     * el ID recién creado.
     *
     * @static
     * @throws Exception si la operacion fallo.
     * @param ProblemsTags [$Problems_Tags] El objeto de tipo ProblemsTags
     * @return Un entero mayor o igual a cero identificando el número de filas afectadas.
     */
    final public static function save(ProblemsTags $Problems_Tags) {
        if (is_null(self::getByPK($Problems_Tags->problem_id, $Problems_Tags->tag_id))) {
            return ProblemsTagsDAOBase::create($Problems_Tags);
        }
        return ProblemsTagsDAOBase::update($Problems_Tags);
    }

    /**
     * Actualizar registros.
     *
     * @static
     * @return Filas afectadas
     * @param ProblemsTags [$Problems_Tags] El objeto de tipo ProblemsTags a actualizar.
     */
    final public static function update(ProblemsTags $Problems_Tags) {
        $sql = 'UPDATE `Problems_Tags` SET `public` = ?, `autogenerated` = ? WHERE `problem_id` = ? AND `tag_id` = ?;';
        $params = [
            $Problems_Tags->public,
            $Problems_Tags->autogenerated,
            $Problems_Tags->problem_id,
            $Problems_Tags->tag_id,
        ];
        global $conn;
        $conn->Execute($sql, $params);
        return $conn->Affected_Rows();
    }

    /**
     * Obtener {@link ProblemsTags} por llave primaria.
     *
     * Este metodo cargará un objeto {@link ProblemsTags} de la base
     * de datos usando sus llaves primarias.
     *
     * @static
     * @return @link ProblemsTags Un objeto del tipo {@link ProblemsTags}. NULL si no hay tal registro.
     */
    final public static function getByPK($problem_id, $tag_id) {
        if (is_null($problem_id) || is_null($tag_id)) {
            return null;
        }
        $sql = 'SELECT `Problems_Tags`.`problem_id`, `Problems_Tags`.`tag_id`, `Problems_Tags`.`public`, `Problems_Tags`.`autogenerated` FROM Problems_Tags WHERE (problem_id = ? AND tag_id = ?) LIMIT 1;';
        $params = [$problem_id, $tag_id];
        global $conn;
        $rs = $conn->GetRow($sql, $params);
        if (empty($rs)) {
            return null;
        }
        return new ProblemsTags($rs);
    }

    /**
     * Eliminar registros.
     *
     * Este metodo eliminará el registro identificado por la llave primaria en
     * el objeto ProblemsTags suministrado. Una vez que se ha
     * eliminado un objeto, este no puede ser restaurado llamando a
     * {@link save()}, ya que este último creará un nuevo registro con una
     * llave primaria distinta a la que estaba en el objeto eliminado.
     *
     * Si no puede encontrar el registro a eliminar, {@link Exception} será
     * arrojada.
     *
     * @static
     * @throws Exception Se arroja cuando no se encuentra el objeto a eliminar en la base de datos.
     * @param ProblemsTags [$Problems_Tags] El objeto de tipo ProblemsTags a eliminar
     */
    final public static function delete(ProblemsTags $Problems_Tags) {
        $sql = 'DELETE FROM `Problems_Tags` WHERE problem_id = ? AND tag_id = ?;';
        $params = [$Problems_Tags->problem_id, $Problems_Tags->tag_id];
        global $conn;

        $conn->Execute($sql, $params);
        if ($conn->Affected_Rows() == 0) {
            throw new NotFoundException('recordNotFound');
        }
    }

    /**
     * Obtener todas las filas.
     *
     * Esta funcion leerá todos los contenidos de la tabla en la base de datos
     * y construirá un arreglo que contiene objetos de tipo {@link ProblemsTags}.
     * Este método consume una cantidad de memoria proporcional al número de
     * registros regresados, así que sólo debe usarse cuando la tabla en
     * cuestión es pequeña o se proporcionan parámetros para obtener un menor
     * número de filas.
     *
     * @static
     * @param $pagina Página a ver.
     * @param $filasPorPagina Filas por página.
     * @param $orden Debe ser una cadena con el nombre de una columna en la base de datos.
     * @param $tipoDeOrden 'ASC' o 'DESC' el default es 'ASC'
     * @return Array Un arreglo que contiene objetos del tipo {@link ProblemsTags}.
     */
    final public static function getAll($pagina = null, $filasPorPagina = null, $orden = null, $tipoDeOrden = 'ASC') {
        $sql = 'SELECT `Problems_Tags`.`problem_id`, `Problems_Tags`.`tag_id`, `Problems_Tags`.`public`, `Problems_Tags`.`autogenerated` from Problems_Tags';
        global $conn;
        if (!is_null($orden)) {
            $sql .= ' ORDER BY `' . mysqli_real_escape_string($conn->_connectionID, $orden) . '` ' . ($tipoDeOrden == 'DESC' ? 'DESC' : 'ASC');
        }
        if (!is_null($pagina)) {
            $sql .= ' LIMIT ' . (($pagina - 1) * $filasPorPagina) . ', ' . (int)$filasPorPagina;
        }
        $rs = $conn->Execute($sql);
        $allData = [];
        foreach ($rs as $row) {
            $allData[] = new ProblemsTags($row);
        }
        return $allData;
    }

    /**
     * Crear registros.
     *
     * Este metodo creará una nueva fila en la base de datos de acuerdo con los
     * contenidos del objeto ProblemsTags suministrado.
     *
     * @static
     * @return Un entero mayor o igual a cero identificando el número de filas afectadas.
     * @param ProblemsTags [$Problems_Tags] El objeto de tipo ProblemsTags a crear.
     */
    final public static function create(ProblemsTags $Problems_Tags) {
        if (is_null($Problems_Tags->public)) {
            $Problems_Tags->public = '0';
        }
        if (is_null($Problems_Tags->autogenerated)) {
            $Problems_Tags->autogenerated = '0';
        }
        $sql = 'INSERT INTO Problems_Tags (`problem_id`, `tag_id`, `public`, `autogenerated`) VALUES (?, ?, ?, ?);';
        $params = [
            $Problems_Tags->problem_id,
            $Problems_Tags->tag_id,
            $Problems_Tags->public,
            $Problems_Tags->autogenerated,
        ];
        global $conn;
        $conn->Execute($sql, $params);
        $ar = $conn->Affected_Rows();
        if ($ar == 0) {
            return 0;
        }

        return $ar;
    }
}
