// Mock bootstrap-vue for Jest tests to avoid Vue 3 compat issues.
// In Vue 3, unknown custom elements (<b-button>, <b-card>, etc.)
// are rendered as native HTML elements, so slot content is preserved.
// By making plugins no-ops, we let Vue 3 handle bootstrap tags natively.

const noopPlugin = {
  install() {},
};

module.exports = {
  // Plugins used in components
  ButtonPlugin: noopPlugin,
  DropdownPlugin: noopPlugin,
  LayoutPlugin: noopPlugin,
  TabsPlugin: noopPlugin,
  CardPlugin: noopPlugin,
  TablePlugin: noopPlugin,
  ModalPlugin: noopPlugin,
  FormInputPlugin: noopPlugin,
  PopoverPlugin: noopPlugin,
  BadgePlugin: noopPlugin,
  PaginationPlugin: noopPlugin,
  CollapsePlugin: noopPlugin,
  IconsPlugin: noopPlugin,
  BootstrapVue: noopPlugin,
  BootstrapVueIcons: noopPlugin,

  // Components that might be imported directly
  BButton: {},
  BCard: {},
  BModal: {},
  BTable: {},
  BFormInput: {},
  BFormSelect: {},
  BFormTextarea: {},
  BFormCheckbox: {},
  BFormGroup: {},
  BForm: {},
  BDropdown: {},
  BDropdownItem: {},
  BDropdownDivider: {},
  BDropdownHeader: {},
  BPopover: {},
  BAlert: {},
  BBadge: {},
  BBreadcrumb: {},
  BBreadcrumbItem: {},
  BCardBody: {},
  BCardHeader: {},
  BCardText: {},
  BCol: {},
  BCollapse: {},
  BContainer: {},
  BIconPencilFill: {},
  BIconTrashFill: {},
  BIconPlus: {},
  BIconCheck: {},
  BIconX: {},
  BIconArrowLeftCircleFill: {},
  BIconArrowRightCircleFill: {},
  BIconCaretDownSquare: {},
  BIconCaretUpSquare: {},
  BIconCheckCircleFill: {},
  BIconChevronDown: {},
  BIconChevronLeft: {},
  BIconChevronRight: {},
  BIconCloudDownload: {},
  BIconPrinter: {},
  BIconQuestionCircleFill: {},
  BIconXCircleFill: {},
  BNav: {},
  BNavItem: {},
  BPagination: {},
  BRow: {},
  BSidebar: {},
  BTab: {},
  BTabs: {},
};
