codecov:
  require_ci_to_pass: yes
  strict_yaml_branch: master

coverage:
  status:
    project:
      php:
        flags:
          - php
      javascript:
        flags:
          - javascript

flags:
  php:
    paths:
      - frontend/server/
  javascript:
    paths:
      - frontend/www/

ignore:
  - ^frontend/server/lib/third_party/.*
  - ^frontend/server/src/DAO/Base/.*
  - ^frontend/server/src/DAO/VO/.*
  - ^frontend/www/js/omegaup/api.ts$
  - ^frontend/www/js/omegaup/api_types.ts$
  - ^frontend/www/third_party/.*
