<template>
  <div class="wait_for_ajax panel panel-default" id="problems_list">
    <div class="panel-heading">
      <h3 class="panel-title">{{ T.wordsProblems }}</h3>
    </div>
    <table class="table problem-list">
      <thead>
        <tr>
          <th class="contains-long-desc">{{ T.wordsTitle }}</th>
          <th class="numericColumn">{{ T.wordsQuality }}</th>
          <th class="numericColumn">{{ T.wordsDifficulty }}</th>
          <th class="numericColumn">{{ T.wordsRatio }}</th>
          <th class="numericColumn">
            {{ T.wordsPointsForRank }}
            <a rel="tooltip" href="https://blog.omegaup.com/el-nuevo-ranking-de-omegaup/" data-toggle="tooltip" title v-bind:data-original-title="T.wordsPointsForRankTooltip"><img src="/media/question.png"/></a>
          </th>
          <th v-if="loggedIn == '1'" class="numericColumn">{{ T.wordsMyScore }}</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="problem in problems" v-bind:class="problem.visibility >= 2 ? 'high-quality':''">
          <td>
            <span v-if="problem.visibility < 0" class="glyphicon glyphicon-ban-circle" title="T.wordsBannedProblem"></span>
            <span v-else-if="problem.visibility == 0" class="glyphicon glyphicon-eye-close" title="T.wordsPrivate"></span>
            <img v-else-if="problem.visibility >= 2" src="/media/quality-badge-sm.png" title="T.wordsHighQualityProblem"/>
            <a v-bind:href="`/arena/problem/${problem.alias}`">{{ problem.title }}</a>
            <div v-if="problem.tags.length" class="tag-list" v-bind:title="`${problem.tags.map(tag => tag.name).join(' ')}`">
              <a v-for="tag in problem.tags" v-bind:class="tag.autogenerated === '1' ? 'tag-autogenerated':'tag'" v-bind:href="`/problem/?tag[]=${currentTags ? `${currentTags.join('&tag[]=')}${currentTags.includes(tag.name) ? '':`&tag[]=${tag.name}`}` : `${tag.name}`}`">{{ tag.name }}</a>
            </div>
          </td>
          <td v-if="problem.quality === null" class="numericColumn">—</td>
          <td v-else class="tooltip_column">
            <span v-bind:data-wenk="`${parseFloat(problem.quality).toFixed(1)} ${T.wordsOutOf4}`" data-wenk-pos="right">{{ qualityTags[parseInt(problem.quality)] }}</span>
          </td>
          <td v-if="problem.difficulty === null" class="numericColumn">—</td>
          <td v-else class="tooltip_column">
            <span v-bind:data-wenk="`${parseFloat(problem.difficulty).toFixed(1)} ${T.wordsOutOf4}`" data-wenk-pos="right">{{ difficultyTags[parseInt(problem.difficulty)] }}</span>
          </td>
          <td class="numericColumn">{{ parseFloat(100.0 * problem.ratio).toFixed(2) }}%</td>
          <td class="numericColumn">{{ parseFloat(problem.points).toFixed(2) }}</td>
          <td v-if="loggedIn == '1'" class="numericColumn">{{ parseFloat(problem.score).toFixed(2) }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<style>
.tag, .tag-autogenerated {
  margin-right: .25em;
}
</style>

<script>
import {T} from '../../omegaup.js';
export default {
  props: {
    problems: Array,
    loggedIn: String,
    currentTags: Array,
  },
  data: function() {
    return {
      T: T,
      qualityTags: [T.wordsPoor, T.wordsFair, T.wordsGood, T.wordsExcellent, T.wordsExcellent],
      difficultyTags: [T.wordsVeryEasy, T.wordsEasy, T.wordsMedium,T.wordsHard, T.wordsHard],
    }
  },
}
</script>