# GitHub Actions reversemap for omegaup project
# Maps action references to their immutable commit hashes

actions/checkout:
  tag: v4
  sha: 34e114876b0b11c390a56381ad16ebd13914f8d5
  sha-url: https://github.com/actions/checkout/commit/34e114876b0b11c390a56381ad16ebd13914f8d5
  tag-url: https://github.com/actions/checkout/tree/v4

actions/setup-python:
  tag: v5
  sha: a26af69be951a213d495a4c3e4e4022e16d87065
  sha-url: https://github.com/actions/setup-python/commit/a26af69be951a213d495a4c3e4e4022e16d87065
  tag-url: https://github.com/actions/setup-python/tree/v5

actions/upload-artifact:
  tag: v4
  sha: ea165f8d65b6e75b540449e92b4886f43607fa02
  sha-url: https://github.com/actions/upload-artifact/commit/ea165f8d65b6e75b540449e92b4886f43607fa02
  tag-url: https://github.com/actions/upload-artifact/tree/v4

cirrus-actions/rebase:
  tag: 1.8
  sha: b87d48154a87a85666003575337e27b8cd65f691
  sha-url: https://github.com/cirrus-actions/rebase/commit/b87d48154a87a85666003575337e27b8cd65f691
  tag-url: https://github.com/cirrus-actions/rebase/tree/1.8
