# GitHub Actions reversemap for omegaup project
# Maps action references to their immutable commit hashes

actions/checkout:
  tag: v4
  sha: 34e114876b0b11c390a56381ad16ebd13914f8d5
  sha-url: https://github.com/actions/checkout/commit/34e114876b0b11c390a56381ad16ebd13914f8d5
  tag-url: https://github.com/actions/checkout/tree/v4
actions/setup-python:
  tag: v5
  sha: a26af69be951a213d495a4c3e4e4022e16d87065
  sha-url: https://github.com/actions/setup-python/commit/a26af69be951a213d495a4c3e4e4022e16d87065
  tag-url: https://github.com/actions/setup-python/tree/v5
actions/upload-artifact:
  tag: v4
  sha: ea165f8d65b6e75b540449e92b4886f43607fa02
  sha-url: https://github.com/actions/upload-artifact/commit/ea165f8d65b6e75b540449e92b4886f43607fa02
  tag-url: https://github.com/actions/upload-artifact/tree/v4
cirrus-actions/rebase:
  tag: 1.8
  sha: b87d48154a87a85666003575337e27b8cd65f691
  sha-url: https://github.com/cirrus-actions/rebase/commit/b87d48154a87a85666003575337e27b8cd65f691
  tag-url: https://github.com/cirrus-actions/rebase/tree/1.8
actions/github-script:
  sha: f28e40c7f34bde8b3046d885e986cb6290c5673b
  sha-url: https://github.com/actions/github-script/commit/f28e40c7f34bde8b3046d885e986cb6290c5673b
  tag: v7
  tag-url: https://github.com/actions/github-script/tree/v7
takanome-dev/assign-issue-action:
  sha: d9515870cda43f62505e7c3617f16965f1d40df0
  sha-url: https://github.com/takanome-dev/assign-issue-action/commit/d9515870cda43f62505e7c3617f16965f1d40df0
  tag: beta
  tag-url: https://github.com/takanome-dev/assign-issue-action/tree/beta
actions/labeler:
  sha: 634933edcd8ababfe52f92936142cc22ac488b1b
  sha-url: https://github.com/actions/labeler/commit/634933edcd8ababfe52f92936142cc22ac488b1b
  tag: v6
  tag-url: https://github.com/actions/labeler/tree/v6
codelytv/pr-size-labeler:
  sha: 0b7f116f59d1830881bc1cc88be32b005ab09ffa
  sha-url: https://github.com/codelytv/pr-size-labeler/commit/0b7f116f59d1830881bc1cc88be32b005ab09ffa
  tag: v1
  tag-url: https://github.com/codelytv/pr-size-labeler/tree/v1
actions/stale:
  sha: 997185467fa4f803885201cee163a9f38240193d
  sha-url: https://github.com/actions/stale/commit/997185467fa4f803885201cee163a9f38240193d
  tag: v10
  tag-url: https://github.com/actions/stale/tree/v10
actions/first-interaction:
  sha: 1c4688942c71f71d4f5502a26ea67c331730fa4d
  sha-url: https://github.com/actions/first-interaction/commit/1c4688942c71f71d4f5502a26ea67c331730fa4d
  tag: v3.1.0
  tag-url: https://github.com/actions/first-interaction/tree/v3.1.0
codecov/codecov-action:
  sha: b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238
  sha-url: https://github.com/codecov/codecov-action/commit/b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238
  tag: v4
  tag-url: https://github.com/codecov/codecov-action/tree/v4