apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
- ../../base

resources:
- ingress.yaml

generators:
- argocd-aws-credentials.yaml

patchesStrategicMerge:
- argocd-cm.yaml
- argo-cd-repo-server-ksops-patch.yaml
