apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kustomization

bases:
- ../../base

secretGenerator:
- name: omegaup-secret
  files:
  - omegaup-secret/config.php
- name: frontend-secret
  files:
  - frontend-secret/certificate.pem
  - frontend-secret/key.pem
- name: broadcaster-secret
  files:
  - broadcaster-secret/config.json
  - broadcaster-secret/certificate.pem
  - broadcaster-secret/key.pem
- name: grader-secret
  files:
  - grader-secret/config.json
  - grader-secret/certificate.pem
  - grader-secret/key.pem
- name: runner-secret
  files:
  - runner-secret/config.json
  - runner-secret/certificate.pem
  - runner-secret/key.pem
- name: gitserver-secret
  files:
  - gitserver-secret/config.json

configMapGenerator:
- name: nginx-config
  behavior: merge
  files:
  - nginx-config/php-upstream.conf
  - nginx-config/broadcaster-upstream.conf
  - nginx-config/grader-upstream.conf

resources:
- database.yaml
- backend.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend-deployment
      labels:
        app: frontend
    spec:
      replicas: 1
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: omegaup.local
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: frontend-ingress
