site_name: libinteractive
repo_url: https://github.com/omegaup/libinteractive
docs_dir: .
pages:
- Index: 'index.md'
- Writing problems: 'writing.md'
- Implementation details: 'internals.md'
- Contestants: 'contest.md'
- License: 'license.md'
theme: readthedocs
