apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omegaup

metadata:
  name: kustomization
  namespace: omegaup

resources:
- grader-metrics.yaml

generators:
- grader-metrics-secret.yaml
