// generated by frontend/server/cmd/APITool.php. DO NOT EDIT.
import { controllers } from './api_types';

const API = {
  ACL: controllers.ACL,
  Admin: controllers.Admin,
  Authorization: controllers.Authorization,
  Badge: controllers.Badge,
  Clarification: controllers.Clarification,
  Contest: controllers.Contest,
  Controller: controllers.Controller,
  Course: controllers.Course,
  Grader: controllers.Grader,
  Group: controllers.Group,
  GroupScoreboard: controllers.GroupScoreboard,
  Identity: controllers.Identity,
  Interview: controllers.Interview,
  Notification: controllers.Notification,
  Problem: controllers.Problem,
  ProblemForfeited: controllers.ProblemForfeited,
  Problemset: controllers.Problemset,
  QualityNomination: controllers.QualityNomination,
  Reset: controllers.Reset,
  Run: controllers.Run,
  School: controllers.School,
  Scoreboard: controllers.Scoreboard,
  Session: controllers.Session,
  Submission: controllers.Submission,
  Tag: controllers.Tag,
  Time: controllers.Time,
  User: controllers.User,
};

export { API as default };
