apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- deployment.yaml

configMapGenerator:
- name: fluentbit-config
  files:
  - fluentbit-config/fluent-bit.conf
  - fluentbit-config/parsers.conf
- name: php-config
  files:
  - php-config/php-fpm.conf
- name: nginx-config
  files:
  - nginx-config/nginx.conf
  - nginx-config/mime.types
