site_name: libinteractive
repo_url: https://github.com/omegaup/libinteractive
docs_dir: .
pages:
- Índice: 'index.md'
- Escribiendo problemas: 'writing.md'
- Detalles de implementación: 'internals.md'
- Concursantes: 'contest.md'
- Licencia: 'license.md'
theme: readthedocs
