FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
        ca-certificates \
        curl \
        gnupg2 \
        software-properties-common \
        && \
    /usr/sbin/update-ca-certificates && \
    apt-get autoremove -y && \
    apt-get clean

RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list

RUN add-apt-repository ppa:ondrej/php && \
    apt-get update -y && \
    apt-get install --no-install-recommends -y \
        git \
        mysql-client-core-8.0 \
        nginx \
        nodejs \
        openjdk-16-jre-headless \
        php8.0 \
        php8.0-apcu \
        php8.0-curl \
        php8.0-fpm \
        php8.0-gmp \
        php8.0-mbstring \
        php8.0-mysql \
        php8.0-opcache \
        php8.0-redis \
        php8.0-xml \
        php8.0-zip \
        python3.8-venv \
        sudo \
        supervisor \
        wait-for-it \
        xz-utils \
        yarn \
        && \
    apt-get autoremove -y && \
    apt-get clean

RUN curl -sL https://getcomposer.org/download/2.2.4/composer.phar -o /usr/bin/composer && \
    chmod +x /usr/bin/composer

RUN curl -sL https://github.com/omegaup/gitserver/releases/download/v1.8.11/omegaup-gitserver.tar.xz | tar xJ -C /
RUN curl -sL https://github.com/omegaup/libinteractive/releases/download/v2.0.27/libinteractive.jar -o /usr/share/java/libinteractive.jar

RUN useradd --create-home --shell=/bin/bash ubuntu

RUN mkdir -p /etc/omegaup/frontend
RUN mkdir -p /var/log/omegaup && chown -R ubuntu /var/log/omegaup
RUN mkdir -p /var/log/supervisor && chown -R ubuntu /var/log/supervisor

COPY ./etc/omegaup/frontend/* /etc/omegaup/frontend/
COPY ./etc/supervisor/* /etc/supervisor/
COPY ./etc/php/8.0/fpm/* /etc/php/8.0/fpm/
COPY ./etc/php/8.0/mods-available/* /etc/php/8.0/mods-available/
COPY ./etc/nginx/* /etc/nginx/
COPY ./etc/sudoers.d/* /etc/sudoers.d/
RUN chmod 440 /etc/sudoers.d/ubuntu
COPY ./usr/bin/* /usr/bin/
RUN chmod +x /usr/bin/yarn-dev.sh /usr/bin/developer-environment.sh
COPY ./my.cnf /home/ubuntu/.my.cnf

RUN mkdir /opt/omegaup && chown -R ubuntu /opt/omegaup
USER ubuntu
WORKDIR /opt/omegaup

EXPOSE 8001

ENV CI=false
ENV VIRTUAL_ENV=/opt/omegaup/stuff/venv
ENV PATH=/opt/omegaup/stuff/venv/bin:$PATH

CMD ["wait-for-it", "grader:36663", "gitserver:33861", "broadcaster:22291", "mysql:13306", "--", \
     "/bin/bash", "-c", \
     "while [[ ! -d /opt/omegaup/frontend/server ]]; do sleep 1; done; exec /usr/bin/supervisord"]
