FROM omegaup/local-backend-base-builder

ENV DEBIAN_FRONTEND=noninteractive
USER root
RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
        ca-certificates \
        curl \
        openjdk-18-jre-headless \
        && \
    /usr/sbin/update-ca-certificates && \
    apt-get autoremove -y && \
    apt-get clean

RUN curl -sL https://github.com/omegaup/libinteractive/releases/download/v2.0.27/libinteractive.jar \
        -o /usr/share/java/libinteractive.jar

ADD go/go.mod /home/ubuntu/go/omegaup/
ADD go/Makefile /home/ubuntu/go/omegaup/
RUN chown -R ubuntu:ubuntu /home/ubuntu/go/
USER ubuntu

CMD ["/bin/bash"]
