FROM ubuntu:bionic

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y && \
    apt install --no-install-recommends -y curl ca-certificates && \
    /usr/sbin/update-ca-certificates && \
    apt autoremove -y && \
    apt clean

RUN curl -sL https://deb.nodesource.com/setup_13.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list

RUN apt update -y && \
    apt install --no-install-recommends -y \
        php7.2-fpm php7.2-curl php7.2-mysql php7.2-sqlite3 php7.2-zip \
        php7.2-mbstring php7.2-json php7.2-opcache php7.2-xml nginx git \
        yarn nodejs supervisor python3-requests python3-mysqldb \
        mysql-client-core-5.7 sudo wait-for-it && \
    apt autoremove -y && \
    apt clean

RUN curl -sL https://phar.phpunit.de/phpunit-6.5.9.phar -o /usr/bin/phpunit
RUN chmod +x /usr/bin/phpunit
RUN mkdir -p /etc/omegaup/frontend

RUN useradd --create-home --shell=/bin/bash ubuntu

RUN mkdir -p /var/log/omegaup && chown -R ubuntu /var/log/omegaup
RUN mkdir -p /var/log/supervisor && chown -R ubuntu /var/log/supervisor

COPY ./etc/omegaup/frontend/* /etc/omegaup/frontend/
COPY ./etc/supervisor/* /etc/supervisor/
COPY ./etc/php/7.2/fpm/* /etc/php/7.2/fpm/
COPY ./etc/nginx/* /etc/nginx/
COPY ./etc/sudoers.d/* /etc/sudoers.d/
RUN chmod 440 /etc/sudoers.d/ubuntu
COPY ./usr/bin/* /usr/bin/
RUN chmod +x /usr/bin/yarn-dev.sh
COPY ./my.cnf /home/ubuntu/.my.cnf

RUN mkdir /opt/omegaup && chown -R ubuntu /opt/omegaup
USER ubuntu
WORKDIR /opt/omegaup

EXPOSE 8000

CMD ["wait-for-it", "grader:11302", "gitserver:33861", "mysql:3306", "--", "/usr/bin/supervisord"]
