INSERT INTO
  States (country_id, name, state_code)
VALUES
  ('US', 'Alabama', 'AL'),
  ('US', 'Alaska', 'AK'),
  ('US', 'Arizona', 'AZ'),
  ('US', 'Arkansas', 'AR'),
  ('US', 'California', 'CA'),
  ('US', 'Colorado', 'CO'),
  ('US', 'Connecticut', 'CT'),
  ('US', 'Delaware', 'DE'),
  ('US', 'District of Columbia', 'DC'),
  ('US', 'Florida', 'FL'),
  ('US', 'Georgia', 'GA'),
  ('US', 'Hawaii', 'HI'),
  ('US', 'Idaho', 'ID'),
  ('US', 'Illinois', 'IL'),
  ('US', 'Indiana', 'IN'),
  ('US', 'Iowa', 'IA'),
  ('US', 'Kansas', 'KS'),
  ('US', 'Kentucky', 'KY'),
  ('US', 'Louisiana', 'LA'),
  ('US', 'Maine', 'ME'),
  ('US', 'Maryland', 'MD'),
  ('US', 'Massachusetts', 'MA'),
  ('US', 'Michigan', 'MI'),
  ('US', 'Minnesota', 'MN'),
  ('US', 'Mississippi', 'MS'),
  ('US', 'Missouri', 'MO'),
  ('US', 'Montana', 'MT'),
  ('US', 'Nebraska', 'NE'),
  ('US', 'Nevada', 'NV'),
  ('US', 'New Hampshire', 'NH'),
  ('US', 'New Jersey', 'NJ'),
  ('US', 'New Mexico', 'NM'),
  ('US', 'New York', 'NY'),
  ('US', 'North Carolina', 'NC'),
  ('US', 'North Dakota', 'ND'),
  ('US', 'Ohio', 'OH'),
  ('US', 'Oklahoma', 'OK'),
  ('US', 'Oregon', 'OR'),
  ('US', 'Pennsylvania', 'PA'),
  ('US', 'Rhode Island', 'RI'),
  ('US', 'South Carolina', 'SC'),
  ('US', 'South Dakota', 'SD'),
  ('US', 'Tennessee', 'TN'),
  ('US', 'Texas', 'TX'),
  ('US', 'Utah', 'UT'),
  ('US', 'Vermont', 'VT'),
  ('US', 'Virginia', 'VA'),
  ('US', 'Washington', 'WA'),
  ('US', 'West Virginia', 'WV'),
  ('US', 'Wisconsin', 'WI'),
  ('US', 'Wyoming', 'WY'),
  ('MX', 'Aguascalientes', 'AG'),
  ('MX', 'Baja California', 'BN'),
  ('MX', 'Baja California Sur', 'BS'),
  ('MX', 'Campeche', 'CM'),
  ('MX', 'Chiapas', 'CP'),
  ('MX', 'Chihuahua', 'CH'),
  ('MX', 'Coahuila', 'CA'),
  ('MX', 'Colima', 'CL'),
  ('MX', 'Distrito Federal', 'DF'),
  ('MX', 'Durango', 'DU'),
  ('MX', 'Guanajuato', 'GJ'),
  ('MX', 'Guerrero', 'GR'),
  ('MX', 'Hidalgo', 'HI'),
  ('MX', 'Jalisco', 'JA'),
  ('MX', 'Mexico', 'MX'),
  ('MX', 'Michoacan', 'MC'),
  ('MX', 'Morelos', 'MR'),
  ('MX', 'Nayarit', 'NA'),
  ('MX', 'Nuevo Leon', 'NL'),
  ('MX', 'Oaxaca', 'OA'),
  ('MX', 'Puebla', 'PU'),
  ('MX', 'Queretaro', 'QE'),
  ('MX', 'Quintana Roo', 'QR'),
  ('MX', 'San Luis Potosi', 'SL'),
  ('MX', 'Sinaloa', 'SI'),
  ('MX', 'Sonora', 'SO'),
  ('MX', 'Tabasco', 'TB'),
  ('MX', 'Tamaulipas', 'TM'),
  ('MX', 'Tlaxcala', 'TL'),
  ('MX', 'Veracruz', 'VE'),
  ('MX', 'Yucatan', 'YU'),
  ('MX', 'Zacatecas', 'ZA');
