INSERT INTO
  States (country_id, name, state_code)
VALUES
  ('PE', 'Amazonas', 'AM'),
  ('PE', 'Áncash', 'AN'),
  ('PE', 'Apurímac', 'AP'),
  ('PE', 'Arequipa', 'AR'),
  ('PE', 'Ayacucho', 'AY'),
  ('PE', 'Cajamarca', 'CJ'),
  ('PE', 'Callao', 'CL'),
  ('PE', 'Cusco', 'CS'),
  ('PE', 'Huancavelica', 'HC'),
  ('PE', 'Huánuco', 'HU'),
  ('PE', 'Ica', 'IC'),
  ('PE', 'Junín', 'JU'),
  ('PE', 'La Libertad', 'LL'),
  ('PE', 'Lambayeque', 'LY'),
  ('PE', 'Lima Metropolitana', 'LM'),
  ('PE', 'Lima (departamento)', 'LD'),
  ('PE', 'Loreto', 'LO'),
  ('PE', 'Madre de Dios', 'MA'),
  ('PE', 'Moquegua', 'MO'),
  ('PE', 'Pasco', 'PA'),
  ('PE', 'Piura', 'PI'),
  ('PE', 'Puno', 'PU'),
  ('PE', 'San Martín', 'SA'),
  ('PE', 'Tacna', 'TA'),
  ('PE', 'Tumbes', 'TU'),
  ('PE', 'Ucayali', 'UC');

