ALTER TABLE
    `Problems_Tags`
ADD COLUMN
    `source` enum('owner', 'voted', 'quality') NOT NULL DEFAULT 'owner' COMMENT 'El origen del tag: elegido por el autor, elegido por los usuarios o elegido por un revisor.';

UPDATE
    `Problems_Tags`
SET
    `source` = 'voted'
WHERE
    `autogenerated` = 1;
