ALTER TABLE
    `Problems_Tags`
ADD COLUMN
    `type` enum('author_tag', 'quality_tag', 'crowdsourced_tag') NOT NULL DEFAULT 'author_tag' COMMENT 'El tipo de tag: elegido por el autor, de calidad o elegido por los usuarios.';

UPDATE
    `Problems_Tags`
SET
    `type` = 'crowdsourced_tag'
WHERE
    `autogenerated` = 1;