CREATE TEMPORARY TABLE _TagMapping(
  old_name VARCHAR(75) NOT NULL,
  new_name VARCHAR(75) NOT NULL,
  old_tag_id INT DEFAULT NULL,
  new_tag_id INT DEFAULT NULL);
INSERT INTO _TagMapping(old_name, new_name) VALUES
  ('segment-tree', 'problemTagSegmentTrees'),
  ('grafo-bipartito', 'problemTagBipartiteMatching'),
  ('prefix-sum', 'problemTagPartialSums'),
  ('prefixsum', 'problemTagPartialSums'),
  ('algoritmo-genetico', 'problemTagGeneticAlgorithms'),
  ('genetic-algorithm', 'problemTagGeneticAlgorithms'),
  ('gloton', 'problemTagGreedyAlgorithms'),
  ('greedy', 'problemTagGreedyAlgorithms'),
  ('arboles', 'problemTagTrees'),
  ('tree', 'problemTagTrees'),
  ('mst', 'problemTagMinimumSpanningTrees'),
  ('map', 'problemTagBinarySearchTree'),
  ('set', 'problemTagBinarySearchTree'),
  ('fenwick-tree', 'problemTagFenwickTrees'),
  ('wavelet-tree', 'problemTagWaveletTrees'),
  ('residuos', 'problemTagModularArithmetic'),
  ('aritmetica-modular', 'problemTagModularArithmetic'),
  ('modulo', 'problemTagModularArithmetic'),
  ('manejo-indices', 'problemTagArrays'),
  ('arreglos', 'problemTagArrays'),
  ('vectores', 'problemTagArrays'),
  ('boi', 'problemTagBOI'),
  ('binary-search', 'problemTagBinarySearch'),
  ('busqueda-binaria', 'problemTagBinarySearch'),
  ('pruning', 'problemTagBacktracking'),
  ('backtracking', 'problemTagBacktracking'),
  ('bfs', 'problemTagBreadthFirstSearch'),
  ('busqueda-en-amplitud', 'problemTagBreadthFirstSearch'),
  ('dfs', 'problemTagDepthFirstSearch'),
  ('busqueda-incremental', 'problemTagIncrementalSearch'),
  ('dijkstra', 'problemTagShortestPaths'),
  ('cadenas', 'problemTagCharsAndStrings'),
  ('manipulacion-cadenas', 'problemTagCharsAndStrings'),
  ('strings', 'problemTagCharsAndStrings'),
  ('strings-dp', 'problemTagCharsAndStrings'),
  ('strings-dp', 'problemTagDynamicProgramming'),
  ('convex-hull', 'problemTagConvexHull'),
  ('ciclos', 'problemTagLoops'),
  ('ciclos-anidados', 'problemTagLoops'),
  ('ciclos-con-if', 'problemTagLoops'),
  ('iteracion', 'problemTagLoops'),
  ('iterate', 'problemTagLoops'),
  ('while', 'problemTagLoops'),
  ('ciic', 'problemTagCIIC'),
  ('ciic2018', 'problemTagCIIC'),
  ('coci', 'problemTagCOCI'),
  ('coding-cup', 'problemTagCodingCup'),
  ('coding-rush', 'problemTagCodingRush'),
  ('colas', 'problemTagQueues'),
  ('floodfill', 'problemTagGraphConnectivity'),
  ('strongly-connected-components', 'problemTagGraphConnectivity'),
  ('union-find', 'problemTagDisjointSets'),
  ('dsu', 'problemTagDisjointSets'),
  ('hashin', 'problemTagHashing'),
  ('hash', 'problemTagHashing'),
  ('hashing', 'problemTagHashing'),
  ('divide-and-conquer', 'problemTagDivideAndConquer'),
  ('ecuacion-diofantina', 'problemTagDiophantineEquations'),
  ('easy-inout', 'problemTagInputAndOutput'),
  ('entrada-salida', 'problemTagInputAndOutput'),
  ('imprimir', 'problemTagInputAndOutput'),
  ('lazy-propagation', 'problemTagLazyPropagation'),
  ('potencias', 'problemTagExponentiationBySquaring'),
  ('exponenciacion-rapida', 'problemTagExponentiationBySquaring'),
  ('flujos', 'problemTagMaxFlow'),
  ('busqueda-exhaustiva', 'problemTagBruteForce'),
  ('brute', 'problemTagBruteForce'),
  ('brute-force', 'problemTagBruteForce'),
  ('funciones', 'problemTagFunctions'),
  ('criba-de-eratostenes', 'problemTagPrimeGeneration'),
  ('geometrico', 'problemTagAnalyticGeometry'),
  ('heuristica', 'problemTagHeuristics'),
  ('icpc', 'problemTagICPC'),
  ('icpc2014-latam', 'problemTagICPC'),
  ('the-2014-southeast-usa-regional-contest', 'problemTagICPC'),
  ('the-2016-acm-itesg-local-programming-contest', 'problemTagICPC'),
  ('ad-hoc', 'problemTagImplementation'),
  ('adhoc', 'problemTagImplementation'),
  ('implementacion', 'problemTagImplementation'),
  ('implementation', 'problemTagImplementation'),
  ('libinteractive', 'problemTagInteractive'),
  ('ioi', 'problemTagIOI'),
  ('ioi-1617-ps2', 'problemTagIOI'),
  ('mano-derecha', 'problemTagKarel'),
  ('karel-recusirvidad-kinder', 'problemTagKarel'),
  ('karel-recusirvidad-kinder', 'problemTagRecursion'),
  ('karelotitlan-recursion', 'problemTagKarel'),
  ('karelotitlan-recursion', 'problemTagRecursion'),
  ('recursion-con-parametros', 'problemTagKarel'),
  ('recursion-con-parametros', 'problemTagRecursion'),
  ('recursividad-deshabilitada', 'problemTagKarel'),
  ('recursividad-deshabilitada', 'problemTagRecursion'),
  ('recursividad-kinder', 'problemTagKarel'),
  ('listas', 'problemTagLinkedLists'),
  ('bitmask', 'problemTagBitManipulation'),
  ('bits', 'problemTagBitManipulation'),
  ('bits-', 'problemTagBitManipulation'),
  ('recorrido-matrices', 'problemTagMatrices'),
  ('matrices', 'problemTagMatrices'),
  ('matrices-cadenas', 'problemTagMatrices'),
  ('matrices-cadenas', 'problemTagCharsAndStrings'),
  ('memorizacion', 'problemTagMemorization'),
  ('meet-in-the-middle', 'problemTagMeetInTheMiddle'),
  ('fracciones', 'problemTagGCDAndLCM'),
  ('gcd', 'problemTagGCDAndLCM'),
  ('lca', 'problemTagGCDAndLCM'),
  ('bignum', 'problemTagBigNumbers'),
  ('numeros-grandes', 'problemTagBigNumbers'),
  ('omi', 'problemTagOMI'),
  ('omi2010', 'problemTagOMI'),
  ('omi2015', 'problemTagOMI'),
  ('omi-2016', 'problemTagOMI'),
  ('omi2016', 'problemTagOMI'),
  ('omi-2017', 'problemTagOMI'),
  ('omi2017', 'problemTagOMI'),
  ('omi2018', 'problemTagOMI'),
  ('omi-2019', 'problemTagOMI'),
  ('estatal-aguascalientes', 'problemTagOMIAguascalientes'),
  ('estatal-aguascalientes', 'problemTagOMI'),
  ('omibc', 'problemTagOMIBajaCalifornia'),
  ('omibc', 'problemTagOMI'),
  ('omibc-2016', 'problemTagOMI'),
  ('omibc-2016', 'problemTagOMIBajaCalifornia'),
  ('campeche', 'problemTagOMICampeche'),
  ('campeche', 'problemTagOMI'),
  ('chihuahua', 'problemTagOMIChihuahua'),
  ('chihuahua', 'problemTagOMI'),
  ('oieg', 'problemTagOMIGuanajuato'),
  ('oieg', 'problemTagOMI'),
  ('orig', 'problemTagOMIGuanajuato'),
  ('orig', 'problemTagOMI'),
  ('omiijal', 'problemTagOMIJalisco'),
  ('omiijal', 'problemTagOMI'),
  ('omijal', 'problemTagOMIJalisco'),
  ('omijal', 'problemTagOMI'),
  ('tabasco', 'problemTagOMITabasco'),
  ('tabasco', 'problemTagOMI'),
  ('olimpiada-veracruzana-de-informatica-2019', 'problemTagOMIVeracruz'),
  ('olimpiada-veracruzana-de-informatica-2019', 'problemTagOMI'),
  ('olimpiada-veracruzana-de-informatica-2019-ovi-2019', 'problemTagOMIVeracruz'),
  ('olimpiada-veracruzana-de-informatica-2019-ovi-2019', 'problemTagOMI'),
  ('ovi', 'problemTagOMIVeracruz'),
  ('ovi', 'problemTagOMI'),
  ('preselectivo-nacional-ovi', 'problemTagOMIVeracruz'),
  ('preselectivo-nacional-ovi', 'problemTagOMI'),
  ('preselectivonacional-ovi', 'problemTagOMIVeracruz'),
  ('preselectivonacional-ovi', 'problemTagOMI'),
  ('problema-de-olimpiada-veracruzana-de-informatica-2', 'problemTagOMIVeracruz'),
  ('problema-de-olimpiada-veracruzana-de-informatica-2', 'problemTagOMI'),
  ('omip', 'problemTagOMIPS'),
  ('omips', 'problemTagOMIPS'),
  ('omip2017', 'problemTagOMIPS'),
  ('omips2017', 'problemTagOMIPS'),
  ('omis2017', 'problemTagOMIPS'),
  ('omips2018', 'problemTagOMIPS'),
  ('omips2019', 'problemTagOMIPS'),
  ('omips2020', 'problemTagOMIPS'),
  ('counting-sort', 'problemTagSorting'),
  ('burbuja', 'problemTagSorting'),
  ('ordenamiento', 'problemTagSorting'),
  ('sorting', 'problemTagSorting'),
  ('topological-sort', 'problemTagTopologicalSorting'),
  ('next-permutation', 'problemTagPermutations'),
  ('suma-acumulada', 'problemTagPartialSums'),
  ('pilas-y-colas', 'problemTagStacks'),
  ('pilas-y-colas', 'problemTagQueues'),
  ('pilas', 'problemTagStacks'),
  ('combinatoria', 'problemTagCountingProblems'),
  ('conteo', 'problemTagCountingProblems'),
  ('counting', 'problemTagCountingProblems'),
  ('knapsack', 'problemTagDynamicProgramming'),
  ('lis', 'problemTagDynamicProgramming'),
  ('lis', 'problemTagSubsequenceSearch'),
  ('dp', 'problemTagDynamicProgramming'),
  ('programacion-dinamica', 'problemTagDynamicProgramming'),
  ('recursion', 'problemTagRecursion'),
  ('divisibilidad', 'problemTagDivisibilityRules'),
  ('grafos', 'problemTagGraphRepresentation'),
  ('graph-theory', 'problemTagGraphRepresentation'),
  ('series-numericas', 'problemTagNumericalSeries'),
  ('simulacion', 'problemTagSimulation'),
  ('simulacion7', 'problemTagSimulation'),
  ('ecuacion-cuadratica', 'problemTagSystemsOfEquations'),
  ('two-pointer', 'problemTagTwoPointersTechnique'),
  ('two-pointer-tle', 'problemTagTwoPointersTechnique'),
  ('game-theory', 'problemTagGameTheory'),
  ('min-max', 'problemTagGameTheory'),
  ('teoria-de-numeros', 'problemTagNumberTheory'),
  ('number-theory', 'problemTagNumberTheory'),
  ('if-anidado', 'problemTagConditionals'),
  ('comparacion', 'problemTagConditionals'),
  ('condicionales', 'problemTagConditionals'),
  ('if', 'problemTagConditionals'),
  ('if-else', 'problemTagConditionals'),
  ('if-then-else', 'problemTagConditionals'),
  ('fft', 'problemTagFourierTransformation'),
  ('trie', 'problemTagTries'),
  ('trie-dp', 'problemTagTries'),
  ('trie-dp', 'problemTagDynamicProgramming'),
  ('sliding-window', 'problemTagSlidingWindow'),
  ('bellman', 'problemTagShortestPaths'),
  ('bst', 'problemTagBinarySearchTree'),
  ('dos-punteros', 'problemTagTwoPointersTechnique'),
  ('lista-enlazada', 'problemTagLinkedLists'),
  ('matriz', 'problemTagMatrices'),
  ('pila', 'problemTagStacks'),
  ('suma-de-acumulados', 'problemTagPartialSums'),
  ('tabla-hash', 'problemTagHashing'),
  ('ventana-deslizante', 'problemTagSlidingWindow');

-- Populate the ID mapping table.
UPDATE
  `_TagMapping` AS `tm`,
  `Tags` AS `t`
SET
  `tm`.`old_tag_id` = `t`.`tag_id`
WHERE
  `tm`.`old_name` = `t`.`name`;
UPDATE
  `_TagMapping` AS `tm`,
  `Tags` AS `t`
SET
  `tm`.`new_tag_id` = `t`.`tag_id`
WHERE
  `tm`.`new_name` = `t`.`name`;

-- Insert new relations tag-problem
INSERT IGNORE INTO `Problems_Tags` (`problem_id`, `tag_id`, `public`, `source`)
SELECT `pt`.`problem_id`, `tm`.`new_tag_id`, '1', 'owner'
  FROM `Problems_Tags` AS `pt`
  INNER JOIN `_TagMapping` AS `tm` 
  ON `pt`.`tag_id` = `tm`.`old_tag_id`;

-- Delete old relations tag-problem
DELETE
  `pt`
FROM
  `Problems_Tags` AS `pt`
INNER JOIN
  `_TagMapping` AS `tm`
ON
  `tm`.`old_tag_id` = `pt`.`tag_id`;

-- Delete all non-localized tags.
DELETE
  `t`
FROM
  `Tags` AS `t`
INNER JOIN
  `_TagMapping` AS `tm`
ON
  `tm`.`old_tag_id` = `t`.`tag_id`;