<?php
/** ******************************************************************************* *
  *                    !ATENCION!                                                   *
  *                                                                                 *
  * Este codigo es generado automaticamente. Si lo modificas tus cambios seran      *
  * reemplazados la proxima vez que se autogenere el codigo.                        *
  *                                                                                 *
  * ******************************************************************************* */

namespace OmegaUp\DAO\VO;

/**
 * Value Object class for table `Problems_Tags`.
 *
 * @access public
 */
class ProblemsTags extends \OmegaUp\DAO\VO\VO {
    const FIELD_NAMES = [
        'problem_id' => true,
        'tag_id' => true,
        'public' => true,
        'autogenerated' => true,
    ];

    function __construct(?array $data = null) {
        if (empty($data)) {
            return;
        }
        $unknownColumns = array_diff_key($data, self::FIELD_NAMES);
        if (!empty($unknownColumns)) {
            throw new \Exception('Unknown columns: ' . join(', ', array_keys($unknownColumns)));
        }
        if (isset($data['problem_id'])) {
            $this->problem_id = (int)$data['problem_id'];
        }
        if (isset($data['tag_id'])) {
            $this->tag_id = (int)$data['tag_id'];
        }
        if (isset($data['public'])) {
            $this->public = boolval($data['public']);
        }
        if (isset($data['autogenerated'])) {
            $this->autogenerated = boolval($data['autogenerated']);
        }
    }

    /**
     * [Campo no documentado]
     * Llave Primaria
     *
     * @var int|null
     */
    public $problem_id = null;

    /**
     * [Campo no documentado]
     * Llave Primaria
     *
     * @var int|null
     */
    public $tag_id = null;

    /**
     * [Campo no documentado]
     *
     * @var bool
     */
    public $public = false;

    /**
     * Indica si la etiqueta fue generada automaticamente a partir de votos de los usuarios
     *
     * @var bool
     */
    public $autogenerated = false;
}
