<?php

/*
 *  Abstract class to implement validators
 * 
 */
abstract class Validator
{
    // Container of errors generated by the Validator
    private $errors;
    
    // Validator constructor
    public function Validator()
    {
        $this->errors = array();        
    }
    
    // Each validator should implement validate
    abstract public function validate($value);
    
    // Add an error message 
    public function setError($msg)
    {
        $this->errors[] = $msg;
        
    }
    
    // Pops the last error message 
    public function getError()
    {
        return array_pop($this->errors);
    
    }
}

?>
