#!/usr/bin/python

import argparse
import codecs
from glob import glob
import os.path
import re
import string
import subprocess
import sys

TEMPLATES_PATH = 'frontend/templates'
JS_TEMPLATES_PATH = 'frontend/www/js/omegaup'
PSEUDOLOC = 'pseudo'
LINE_RE = re.compile(r'\s+=\s+')
VALUE_RE = re.compile('^"([^"]|\\")*"$')

class colors:
	HEADER = '\033[95m'
	OKGREEN = '\033[92m'
	FAIL = '\033[91m'
	NORMAL = '\033[0m'

parser = argparse.ArgumentParser(description='i18n tool')
parser.add_argument('--validate', dest='validate', action='store_true',
		default=False, help='Only validates, does not make changes')

parser.add_argument('--fill-missing-with-english', dest='fillmissing', action='store_true',
		default=False, help='Fill missing words with the english version of it')

args = parser.parse_args()

root_dir = subprocess.check_output(['/usr/bin/git', 'rev-parse', '--show-toplevel']).strip()
templates_dir = os.path.join(root_dir, TEMPLATES_PATH)
js_templates_dir = os.path.join(root_dir, JS_TEMPLATES_PATH)
pseudoloc_file = os.path.join(templates_dir, PSEUDOLOC + '.lang')
strings = {}
languages = set([PSEUDOLOC])
not_sorted = set()

for lang_path in glob(os.path.join(templates_dir, '*.lang')):
	lang_filename = os.path.basename(lang_path)
	lang = os.path.splitext(lang_filename)[0]
	languages.add(lang)
	last_key = ''
	with codecs.open(lang_path, 'r', 'utf-8') as lang_file:
		for lineno, line in enumerate(lang_file):
			try:
				key, value = LINE_RE.split(line.strip(), 1)
				if last_key >= key:
					not_sorted.add(lang)
				last_key = key
				if key not in strings:
					strings[key] = {}
				if VALUE_RE.match(value) is None:
					raise Exception("Invalid value")
				strings[key][lang] = value
			except:
				print >> sys.stderr, 'Invalid i18n line "%s" in %s:%d' % (
						line.strip(), lang_path, lineno + 1)
				sys.exit(1)

errors = False
if args.validate and not_sorted:
	print >> sys.stderr, 'Entries in %s are not sorted.' % ', '.join(sorted(not_sorted))
	errors = True


if args.fillmissing:
	for key, values in strings.iteritems():
		missing_languages = languages.difference(values.keys())
		if missing_languages:
			print >> sys.stderr, 'Fixing %s%s for %s%s' % (colors.HEADER, key, lang, colors.NORMAL)
			english_word = values['en']
			for lang in sorted(languages):
				if lang not in values:
					with codecs.open(templates_dir + "/" + lang+".lang", 'a', 'utf-8') as myfile:
						print >> myfile, '%s = %s' % (key, english_word)
	print >> sys.stderr, 'Done fixing your missing files, re-run this tool again as usual.'
	sys.exit(0)

for key, values in strings.iteritems():
	missing_languages = languages.difference(values.keys())
	if not args.validate and PSEUDOLOC in missing_languages:
		missing_languages.remove(PSEUDOLOC)
	if missing_languages:
		print >> sys.stderr, '%s%s%s' % (colors.HEADER, key, colors.NORMAL)
		for lang in sorted(languages):
			if lang in values:
				print >> sys.stderr, '\t%s%-10s%s %s' % (colors.OKGREEN, lang, colors.NORMAL, values[lang])
			else:
				print >> sys.stderr, '\t%s%-10s%s missing%s' % (colors.OKGREEN, lang, colors.FAIL, colors.NORMAL)
		errors = True

if errors:
	if args.validate:
		print >> sys.stderr, 'i18n validation errors. Please run %s to fix them.' % sys.argv[0]
	else:
		print >> sys.stderr, 'i18n validation errors. Please fix them manually.'
	sys.exit(1)

if args.validate:
	sys.exit(0)

def pseudoloc(s):
	healthy = u'elsot'
	yummy = u'31507'
	table = dict([(ord(healthy[i]), yummy[i]) for i in xrange(len(healthy))] + [(ord(u'"'), u'')])
	tokens = re.split('(%\([a-zA-Z0-9_-]+\))', s)
	for i in xrange(len(tokens)):
	    if tokens[i].startswith('%(') and tokens[i].endswith(')'):
		continue
	    tokens[i] = tokens[i].translate(table)
	return u'"(%s)"' % ''.join(tokens)

for key, values in strings.iteritems():
	if key == 'locale':
	    values[PSEUDOLOC] = '"pseudo"'
	else:
	    values[PSEUDOLOC] = pseudoloc(values['en'])

for lang in languages:
	lang_path = os.path.join(templates_dir, lang + '.lang')
	with codecs.open(lang_path, 'w', 'utf-8') as lang_file:
		for key in sorted(strings.keys()):
			lang_file.write('%s = %s\n' % (key, strings[key][lang]))
	js_lang_path = os.path.join(js_templates_dir, 'lang.%s.js' % lang)
	with codecs.open(js_lang_path, 'w', 'utf-8') as lang_file:
		lang_file.write('// generated by stuff/i18n.py. DO NOT EDIT.\n')
		lang_file.write('var omegaup = omegaup || {};\n\n')
		lang_file.write('omegaup.T = {\n')
		for key in sorted(strings.keys()):
			lang_file.write('\t%s: %s,\n' % (key, strings[key][lang]))
		lang_file.write('};\n')

# vim: noexpandtab
