"""Type stubs for token_utils module"""
from typing import Optional

def get_token(provided_token: Optional[str] = None) -> str: ...
def parse_token_from_args() -> Optional[str]: ...
def parse_url_from_args() -> Optional[str]: ...