# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "omegaup-trusty"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  # Redirige localhost:8080 hacia el puerto 80 de la VM
  config.vm.network :forwarded_port, guest: 80, host: 8080

  # Permite usar las llaves SSH del host en la VM
  config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |vb|
    # Compilar grader y runner necesita al menos 2GB de memoria
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # Instala todo usando el script.
  config.vm.provision :shell, :privileged => false, :path => "https://raw.github.com/omegaup/omegaup/master/stuff/install.sh"

 # Sincronizar folder con vagrant
  config.vm.synced_folder "~/Documents/omegaup/omegaup/", "/opt/omegaup", type: "rsync",
    rsync__exclude: ".git/",
    rsync__args: "-rv",
    disabled: true
end
