#!/bin/sh -e

OMEGAUP_ROOT=`/usr/bin/git rev-parse --show-toplevel`

/usr/bin/python $OMEGAUP_ROOT/stuff/i18n.py --validate
/usr/bin/python $OMEGAUP_ROOT/stuff/update-templates.py --validate
/usr/bin/python $OMEGAUP_ROOT/stuff/whitespace-purge.py --validate --pre-push $1
/usr/bin/python $OMEGAUP_ROOT/stuff/php-format.py --validate --pre-push $1
