{include file='problem_search_bar.tpl'}
{$qualityTags = [#wordsPoor#, #wordsFair#, #wordsGood#, #wordsExcellent#, #wordsExcellent#]}
{$difficultyTags = [#wordsVeryEasy#, #wordsEasy#, #wordsMedium#, #wordsHard#, #wordsHard#]}
<div class="wait_for_ajax panel panel-default" id="problems_list" >
	<div class="panel-heading">
		<h3 class="panel-title">{#wordsProblems#}</h3>
	</div>
	<table class="table problem-list">
		<thead>
			<tr>
				<th class="contains-long-desc">{#wordsTitle#}</th>
				<th class="numericColumn">{#wordsQuality#}</th>
				<th class="numericColumn">{#wordsDifficulty#}</th>
				<th class="numericColumn">{#wordsRatio#}</th>
				<th class="numericColumn">
					{#wordsPointsForRank#}
					<a rel="tooltip" href="https://blog.omegaup.com/el-nuevo-ranking-de-omegaup/" data-toggle="tooltip" title data-original-title="{#wordsPointsForRankTooltip#}"><img src="/media/question.png"></a>
				</th>
				<th class="numericColumn">{#wordsMyScore#}</th>
			</tr>
		</thead>
		<tbody>
			{foreach item=problem from=$problems}
				<tr {if $problem.visibility >= 2}class="high-quality"{/if}>
				<td>
					{if $problem.visibility < 0} <span class="glyphicon glyphicon-ban-circle" title="{#wordsBannedProblem#}"></span>{/if}
					{if $problem.visibility == 0} <span class="glyphicon glyphicon-eye-close" title="{#wordsPrivate#}"></span>{/if}
					{if $problem.visibility >= 2} <img src="/media/quality-badge-sm.png" title="{#wordsHighQualityProblem#}"></img>{/if}
					<a href="/arena/problem/{$problem.alias}">{$problem.title}</a>
					{if count($problem.tags) > 0}
					<div class="tag-list" title="{foreach item=tag from=$problem.tags}{$tag.name} {/foreach}">
					{foreach item=tag from=$problem.tags}
						{assign var=tagClass value='tag'}
						{if $tag.autogenerated == 1}{assign var=tagClass value='tag-autogenerated'}{/if}
						{if count($current_tags) > 0}
							{if $tag.name|in_array:$current_tags}
							<a class="{$tagClass}" href="/problem/?tag[]={"&tag[]="|implode:$current_tags|escape}">{$tag.name|escape}</a>
							{else}
							<a class="{$tagClass}" href="/problem/?tag[]={"&tag[]="|implode:$current_tags|escape}&tag[]={$tag.name|escape}">{$tag.name|escape}</a>
							{/if}
						{else}
						<a class="{$tagClass}" href="/problem/?tag[]={$tag.name|escape}">{$tag.name|escape}</a>
						{/if}
					{/foreach}
					</div>
					{/if}
				</td>
				{if empty($problem.quality)}
					<td class="numericColumn">&mdash;</td>
				{else}
					<td class="tooltip_column">
						<span data-wenk="{#wordsOutOf4#|replace:'%(Score)':{$problem.quality|string_format:"%.1f"}}" data-wenk-pos="right">
							{$qualityTags[$problem.quality|intval]}
						</span>
					</td>
				{/if}
  				{if empty($problem.difficulty)}
					<td class="numericColumn">&mdash;</td>
  				{else}
					<td class="tooltip_column">
						<span data-wenk="{#wordsOutOf4#|replace:'%(Score)':{$problem.difficulty|string_format:"%.1f"}}" data-wenk-pos="right">
							{$difficultyTags[$problem.difficulty|intval]}
						</span>
					</td>
  				{/if}
				<td class="numericColumn">{100 * $problem.ratio}%</td>
				<td class="numericColumn">{$problem.points}</td>
				<td class="numericColumn">{$problem.score}</td>
				</tr>
			{/foreach}
		</tbody>
	</table>

	{include file='pager_bar.tpl'}
</div>
